app:
  sql:
    config:
      enable: true
#      data:
#        - file:C:/Users/lenovo/Desktop/qqq/
spring:
#  datasource:
#    password: 123456
#    username: root
#    url: jdbc:h2:mem:test1
#  h2:
#    console:
#      path: /h2-console
  datasource:
    url: jdbc:oracle:thin:@10.215.0.124:1521:gsybk
    username: gsybk
    password: gsybk_GSxtyninui