app:
  sql:
    config:
      enable: true
spring:
#  datasource:
#    password: 123456
#    username: root
#    url: jdbc:h2:mem:test1
#  h2:
#    console:
#      path: /h2-console
  datasource:
    url: jdbc:oracle:thin:@10.215.0.126:1521:gsmielecard
    username: gsmielecard
    password: gsmielecard_Gsxtyninui